### ISSUE TITLE
node-tesseract throws error

### ISSUE THREAD

**Issue by HadiIOS** [danschultzer/receipt-scanner#49]
I get an error whenever I try to use receipt-scanner whether if I was using it from CLI or from node. 

the error is 

```
fs.js:165
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:165:11)
    at Object.fs.unlink (fs.js:1034:14)
    at /Users/****/.npm-global/lib/node_modules/receipt-scanner/node_modules/node-tesseract/lib/tesseract.js:99:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

**Comment by danschultzer** [comment]
Thanks for letting me know. It will work now if you pull receipt-scanner from master branch. I'll release a new version later, when I've cleaned up and updated all dependencies.
