### ISSUE TITLE
 npm install receipt-scanner -g doesn't work.

### ISSUE THREAD

**Issue by sungsong88** [danschultzer/receipt-scanner#58]
![image](https://user-images.githubusercontent.com/4941095/48642504-06f1f600-e9ab-11e8-8941-248245686cd5.png)

**Comment by danschultzer** [comment]
Do you have OpenCV installed?

**Comment by sungsong88** [comment]
@danschultzer Yup I did!
<img width="1153" alt="screen shot 2018-11-16 at 4 17 27 pm" src="https://user-images.githubusercontent.com/4941095/48647879-53ddc880-e9bb-11e8-8c83-28b736ac2784.png">

**Comment by danschultzer** [comment]
Try this: `npm install git+https://git@github.com/danschultzer/receipt-scanner.git -g`

**Comment by danschultzer** [comment]
I assume this has been resolved, so I'll close this for now :smile:
